import type { DonorRecord, InventoryRecord, PrototypeRecord } from './types';

export const worklist: PrototypeRecord[] = [
  {
    id: 'POST-02481',
    primary: 'Postulante sintético 01',
    secondary: 'Selección · 09:10',
    tertiary: 'Entrevista pendiente',
    status: 'En evaluación',
    tone: 'blue',
  },
  {
    id: 'DON-01092',
    primary: 'Donante sintético 02',
    secondary: 'Sangre total · 08:42',
    tertiary: 'Unidad BS-2026-01092',
    status: 'Extracción completa',
    tone: 'green',
  },
  {
    id: 'SOL-00641',
    primary: 'Receptor sintético 03',
    secondary: 'Solicitud transfusional · Emergencia',
    tertiary: '2 unidades de glóbulos rojos',
    status: 'Compatibilidad',
    tone: 'purple',
  },
];

export const components: PrototypeRecord[] = [
  {
    id: 'GR-01092-A',
    primary: 'Glóbulos rojos',
    secondary: 'O+ · 280 mL',
    tertiary: 'Origen BS-2026-01092',
    status: 'Cuarentena',
    tone: 'warm-gray',
  },
  {
    id: 'PFC-01092-B',
    primary: 'Plasma fresco congelado',
    secondary: 'O+ · 220 mL',
    tertiary: 'Origen BS-2026-01092',
    status: 'Disponible',
    tone: 'green',
  },
  {
    id: 'PQ-01091-C',
    primary: 'Concentrado de plaquetas',
    secondary: 'A+ · 55 mL',
    tertiary: 'Vence hoy 18:30',
    status: 'Reservado',
    tone: 'purple',
  },
];

export const inventory: InventoryRecord[] = [
  {
    id: 'GR-01088-A',
    component: 'Glóbulos rojos',
    bloodGroup: 'A+',
    location: 'Cámara 01',
    expiresAt: '18/10/2026',
    status: 'Disponible',
    tone: 'green',
    reference: 'BS-2026-01088',
  },
  {
    id: 'GR-01089-A',
    component: 'Glóbulos rojos',
    bloodGroup: 'O-',
    location: 'Cámara 01',
    expiresAt: '20/10/2026',
    status: 'Reservado',
    tone: 'purple',
    reference: 'SOL-00641',
  },
  {
    id: 'PFC-01082-B',
    component: 'Plasma fresco congelado',
    bloodGroup: 'AB+',
    location: 'Congelador 02',
    expiresAt: '14/08/2027',
    status: 'Segregado',
    tone: 'red',
    reference: 'Tamizaje no conforme',
  },
  {
    id: 'PQ-01091-C',
    component: 'Concentrado de plaquetas',
    bloodGroup: 'A+',
    location: 'Agitador 01',
    expiresAt: 'Hoy, 18:30',
    status: 'Próximo a vencer',
    tone: 'warm-gray',
    reference: 'BS-2026-01091',
  },
];

export const auditEvents: PrototypeRecord[] = [
  {
    id: 'EVT-9004',
    primary: 'Unidad reservada',
    secondary: 'GR-01089-A · SOL-00641',
    tertiary: '08/09/2026 10:21 · Profesional sintético',
    status: 'Confirmado',
    tone: 'green',
  },
  {
    id: 'EVT-9003',
    primary: 'Resultado de compatibilidad registrado',
    secondary: 'Compatible · muestra M-00641',
    tertiary: '08/09/2026 10:18 · Laboratorio',
    status: 'Validado',
    tone: 'blue',
  },
  {
    id: 'EVT-9002',
    primary: 'Pre-calificación actualizada',
    secondary: 'POST-02481 · No apto temporal',
    tertiary: '08/09/2026 09:44 · Entrevistador sintético',
    status: 'Versionado',
    tone: 'gray',
  },
];

export const donors: DonorRecord[] = [
  {
    id: 'DON-01092',
    donorCode: 'DON-01092',
    familyName: 'Donante',
    givenName: 'Sintético 02',
    documentType: 'DNI',
    documentNumber: '70000002',
    sex: 'Femenino',
    birthDate: '1992-04-18',
    phone: '999 000 092',
    address: 'Dirección sintética 02',
    placeOfBirth: 'Iquitos',
    origin: 'Iquitos',
    district: 'Punchana',
    province: 'Maynas',
    department: 'Loreto',
    civilStatus: 'Soltera',
    occupation: 'Técnica',
    email: 'donante02@sintetico.local',
    workplace: 'Establecimiento sintético',
    permanence: 'Residente permanente',
    bloodGroup: 'O',
    rhFactor: '+',
    donationCount: 2,
    lastDonationDate: '08/09/2026',
    status: 'Apto para seguimiento',
    donations: [
      {
        id: 'DON-01092-02', date: '08/09/2026', donationType: 'Voluntaria', procedure: 'Sangre total',
        volume: '450 mL', unitCode: 'BS-2026-01092', components: 'GR, PFC, PQ', status: 'Procesada',
        responsible: 'Profesional sintético 01', observation: 'Sin incidencias registradas',
      },
      {
        id: 'DON-01092-01', date: '12/05/2026', donationType: 'Voluntaria', procedure: 'Sangre total',
        volume: '450 mL', unitCode: 'BS-2026-00618', components: 'GR, PFC, PQ', status: 'Transfundida',
        responsible: 'Profesional sintético 02', observation: 'Seguimiento concluido',
      },
    ],
  },
  {
    id: 'DON-01104',
    donorCode: 'DON-01104',
    familyName: 'Donante',
    givenName: 'Sintético 04',
    documentType: 'DNI',
    documentNumber: '70000004',
    sex: 'Masculino',
    birthDate: '1988-11-03',
    phone: '999 000 104',
    address: 'Dirección sintética 04',
    placeOfBirth: 'Lima',
    origin: 'Lima',
    district: 'San Miguel',
    province: 'Lima',
    department: 'Lima',
    civilStatus: 'Casado',
    occupation: 'Ingeniero',
    email: 'donante04@sintetico.local',
    workplace: 'Establecimiento sintético',
    permanence: 'Residente permanente',
    bloodGroup: 'A',
    rhFactor: '-',
    donationCount: 1,
    lastDonationDate: '21/07/2026',
    status: 'Apto para seguimiento',
    donations: [
      {
        id: 'DON-01104-01', date: '21/07/2026', donationType: 'Voluntaria', procedure: 'Aféresis',
        volume: '300 mL', unitCode: 'BS-2026-00874', components: 'Plaquetas', status: 'Disponible',
        responsible: 'Profesional sintético 03', observation: 'Control posterior sin incidencias',
      },
    ],
  },
];
